stages:
  - check
  - test

variables:
  MIX_ENV: test

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

check_warnings:
  stage: check
  image: elixir:1.17.3
  script:
    - MIX_ENV=test mix compile --warnings-as-errors
  only:
    - merge_requests
    - main
    - dev
test:
  stage: test
  image: elixir:1.17.3
  script:
    - MIX_ENV=test mix test
  only:
    - merge_requests
    - main
    - dev
